#!/usr/bin/env python3
from __future__ import annotations

import argparse
import csv
import hashlib
import json
import random
import re
import shutil
import sys
import xml.etree.ElementTree as ET
from pathlib import Path
from typing import Any

sys.path.insert(0, str(Path(__file__).resolve().parents[2]))

from adapters.signal_gps_compare.build_batch import (
	GPS_FIELDS,
	RECON_FIELDS,
	ROAD_SEGMENT_FIELDS,
	SIGNAL_FIELDS,
	GpsTrack,
	Point,
	assign_reconstructions_to_gps,
	bd_mercator_to_wgs_point,
	build_gps_coverage_rows,
	distance_m,
	format_time_ms,
	initialize_batch_dirs,
	parse_datetime_ms,
	parse_gps_filename_window,
	utc_now_iso,
	write_csv,
	write_json,
)


GPS_COVERAGE_THRESHOLD_M = 50.0
GPS_COVERAGE_STEP_M = 20.0
GPS_COVERAGE_SCENARIO_THRESHOLDS_M = (50, 80, 100, 120, 150, 180, 200, 250, 300, 400, 500)
GATE_FIELDS = ["uid", "gate_id", "latitude", "longitude", "timestamp_ms", "source_gps_index", "source_file", "status"]
GATE_TARGET_COUNTS = (4, 5, 4, 5, 4, 4, 5, 4)
GATE_FRACTION_PATTERNS = (
	(0.08, 0.28, 0.57, 0.83),
	(0.12, 0.39, 0.52, 0.76, 0.91),
	(0.06, 0.21, 0.64, 0.88),
	(0.16, 0.34, 0.49, 0.73, 0.94),
)
LBS_FIELDS = [
	"uid",
	"segment_id",
	"point_index",
	"latitude",
	"longitude",
	"timestamp_ms",
	"source_gps_index",
	"source_file",
	"segment_length_m",
	"status",
]
LBS_SHORT_ROUTE_MAX_M = 15_000.0
LBS_COVERAGE_CAP_FRACTION = 0.10
LBS_MIN_SEGMENT_M = 220.0
LBS_TARGET_SEGMENT_RANGE_M = (260.0, 520.0)
LBS_MAX_SEGMENT_M = 560.0
STAY_WINDOW_PAD_S = 30 * 60
STAY_ENDPOINT_SEARCH_RADIUS_M = 1500.0
STAY_RADIUS_MIN_M = 60.0
STAY_RADIUS_MAX_M = 450.0
OD_STAY_EXTRA_FIELDS = [
	"od_type",
	"stay_radius_m",
	"stay_signal_count",
	"stay_unique_cid_count",
	"stay_radius_formula",
	"stay_window_pad_s",
]
MAINROAD_HIGHWAY_PENALTIES = {
	"motorway": 0.75,
	"motorway_link": 0.75,
	"trunk": 0.75,
	"trunk_link": 0.75,
	"primary": 0.85,
	"primary_link": 0.85,
	"secondary": 0.85,
	"secondary_link": 0.85,
	"tertiary": 1.0,
	"tertiary_link": 1.0,
	"residential": 1.25,
	"unclassified": 1.25,
	"living_street": 1.4,
	"service": 1.4,
	"track": 1.4,
}
MAINROAD_DEFAULT_PENALTY = 1.15


def read_json_object(path: Path) -> dict[str, Any]:
	if not path.exists():
		return {}
	try:
		payload = json.loads(path.read_text(encoding="utf-8"))
	except (OSError, json.JSONDecodeError):
		return {}
	return payload if isinstance(payload, dict) else {}


def build_fmm_mechanism_summary(fmm_version: str, network_cost_field: str) -> dict[str, Any]:
	if fmm_version == "mainroad":
		return {
			"name": "mainroad_weighted",
			"summary": "Full-road-network FMM with main-road-preferred routing cost and original geometric anti-detour scoring.",
			"candidate_search": "Candidates are still generated by raw point-to-edge geometry distance, so small roads remain available.",
			"routing_cost": "Dijkstra and UBODT use the network cost field, normally fmm_cost = EPSG:4326 geometry.length * highway_penalty.",
			"transition_distance": "The selected path is scored with original geometric path length for the FMM transition probability, so weighted cost cannot hide detours or loops.",
			"reverse_tolerance": "Reverse tolerance is interpreted in original geometry length units, not weighted cost units.",
			"version_management": "The original FMM binary remains the default; mainroad uses isolated build_mainroad binaries, weighted edges, and a separate UBODT/cache/output namespace.",
			"network_cost_field": network_cost_field or "fmm_cost",
			"highway_penalties": MAINROAD_HIGHWAY_PENALTIES,
			"default_highway_penalty": MAINROAD_DEFAULT_PENALTY,
		}
	return {
		"name": "original",
		"summary": "Original FMM geometric routing and transition scoring.",
		"candidate_search": "Candidates are generated by raw point-to-edge geometry distance.",
		"routing_cost": "Dijkstra and UBODT use original edge geometry length.",
		"transition_distance": "Transition probability uses original geometric shortest-path length.",
		"version_management": "This is the default FMM version and does not require a network cost field.",
		"network_cost_field": network_cost_field,
	}


def collect_v311_algorithm_metadata(v311_root: Path) -> dict[str, Any]:
	source_manifest_path = v311_root / "manifest.json"
	variant_config_path = v311_root.parent / "variant_config.json"
	source_manifest = read_json_object(source_manifest_path)
	variant_config = read_json_object(variant_config_path)
	options = variant_config.get("options") if isinstance(variant_config.get("options"), dict) else {}
	fmm_version = str(source_manifest.get("fmm_version") or options.get("fmm_version") or "original")
	network_cost_field = str(
		source_manifest.get("fmm_network_cost_field")
		or source_manifest.get("network_cost_field")
		or options.get("fmm_network_cost_field")
		or ""
	)
	fmm_edges = str(
		source_manifest.get("fmm_edges")
		or options.get("fmm_edges_mainroad_weighted")
		or options.get("fmm_edges")
		or ""
	)
	metadata: dict[str, Any] = {
		"fmm_version": fmm_version,
		"fmm_network_cost_field": network_cost_field,
		"fmm_edges": fmm_edges,
		"fmm_variant_params": options.get("fmm_variant_params") if isinstance(options.get("fmm_variant_params"), dict) else {},
		"source_manifest_path": str(source_manifest_path) if source_manifest_path.exists() else "",
		"variant_config_path": str(variant_config_path) if variant_config_path.exists() else "",
		"mechanism": build_fmm_mechanism_summary(fmm_version, network_cost_field),
	}
	if variant_config.get("name"):
		metadata["variant_name"] = variant_config["name"]
	if variant_config.get("description"):
		metadata["variant_description"] = variant_config["description"]
	for key in (
		"speed_adaptive_mainroad",
		"speed_sparsity_road_class_prior",
		"speed_cost_rule",
		"route02_startfix",
		"hybrid_strategy",
		"hybrid_route_overrides",
	):
		value = source_manifest.get(key)
		if value is None:
			value = variant_config.get(key)
		if value is None and isinstance(options, dict):
			value = options.get(key)
		if value is not None:
			metadata[key] = value
	return metadata


def parse_float(value: Any) -> float | None:
	try:
		return float(str(value).strip())
	except (TypeError, ValueError):
		return None


def read_points_csv(path: Path) -> list[dict[str, Any]]:
	with path.open(encoding="utf-8", newline="") as handle:
		return list(csv.DictReader(handle))


def row_point(row: dict[str, Any]) -> Point | None:
	lat = parse_float(row.get("latitude") or row.get("lat"))
	lon = parse_float(row.get("longitude") or row.get("lon"))
	if lat is None or lon is None:
		return None
	return Point(lat=lat, lon=lon)


def row_point_wgs(row: dict[str, Any]) -> Point | None:
	return row_point(row)


def read_kml_truth_wgs(path: Path) -> Any:
	from adapters.signal_gps_compare.build_batch import Reconstruction

	ns = {
		"k": "http://www.opengis.net/kml/2.2",
		"gx": "http://www.google.com/kml/ext/2.2",
	}
	root = ET.parse(path).getroot()
	points: list[Point] = []
	source_xy: list[tuple[float, float]] = []
	for element in root.findall(".//gx:coord", ns):
		parts = str(element.text or "").split()
		if len(parts) < 2:
			continue
		lon = parse_float(parts[0])
		lat = parse_float(parts[1])
		if lon is None or lat is None:
			continue
		points.append(Point(lat=lat, lon=lon))
		source_xy.append((lon, lat))
	if not points:
		for element in root.findall(".//k:coordinates", ns):
			for token in str(element.text or "").split():
				parts = token.split(",")
				if len(parts) < 2:
					continue
				lon = parse_float(parts[0])
				lat = parse_float(parts[1])
				if lon is None or lat is None:
					continue
				points.append(Point(lat=lat, lon=lon))
				source_xy.append((lon, lat))
	deduped_points: list[Point] = []
	deduped_source_xy: list[tuple[float, float]] = []
	for point, source in zip(points, source_xy):
		if deduped_points and abs(deduped_points[-1].lat - point.lat) < 1.0e-10 and abs(deduped_points[-1].lon - point.lon) < 1.0e-10:
			continue
		deduped_points.append(point)
		deduped_source_xy.append(source)
	if len(deduped_points) < 2:
		raise ValueError(f"gps truth kml has fewer than 2 usable points: {path}")
	return Reconstruction(path=path, points=deduped_points, source_xy=deduped_source_xy)


def read_gps_truth_wgs(path: Path) -> Any:
	from adapters.signal_gps_compare.build_batch import Reconstruction

	if path.suffix.lower() == ".kml":
		return read_kml_truth_wgs(path)
	points: list[Point] = []
	source_xy: list[tuple[float, float]] = []
	with path.open(encoding="utf-8", newline="") as handle:
		for row in csv.reader(handle):
			if len(row) < 2:
				continue
			x = parse_float(row[0])
			y = parse_float(row[1])
			if x is None or y is None:
				continue
			points.append(bd_mercator_to_wgs_point(x, y))
			source_xy.append((x, y))
	if len(points) < 2:
		raise ValueError(f"gps truth csv has fewer than 2 usable points: {path}")
	return Reconstruction(path=path, points=points, source_xy=source_xy)


def iter_truth_paths(path: Path) -> list[Path]:
	root = path.expanduser().resolve()
	return sorted([*root.glob("*.csv"), *root.glob("*.kml")])


def _path_time_sort_key(path: Path) -> tuple[int, str]:
	digits = "".join(re.findall(r"\d", path.stem))
	return (int(digits[:12]) if len(digits) >= 12 else 0, path.name)


def assign_truth_tracks_to_signal_tracks(truth_tracks: list[Any], signal_tracks: list[GpsTrack]) -> dict[str, Any]:
	kml_truths = [track for track in truth_tracks if track.path.suffix.lower() == ".kml"]
	csv_truths = [track for track in truth_tracks if track.path.suffix.lower() != ".kml"]
	if not kml_truths or not csv_truths or len(truth_tracks) != len(signal_tracks) or len(kml_truths) >= len(signal_tracks):
		return assign_reconstructions_to_gps(truth_tracks, signal_tracks)

	ordered_signals = sorted(signal_tracks, key=lambda track: _path_time_sort_key(track.path))
	kml_signal_paths = {track.path.name for track in ordered_signals[-len(kml_truths):]}
	kml_signals = [track for track in signal_tracks if track.path.name in kml_signal_paths]
	csv_signals = [track for track in signal_tracks if track.path.name not in kml_signal_paths]
	assignments: dict[str, Any] = {}
	if csv_signals:
		assignments.update(assign_reconstructions_to_gps(csv_truths, csv_signals))
	for signal_track, truth_track in zip(
		sorted(kml_signals, key=lambda track: _path_time_sort_key(track.path)),
		sorted(kml_truths, key=lambda track: _path_time_sort_key(track.path)),
	):
		assignments[signal_track.path.name] = truth_track
	return assignments


def read_signal_segment_wgs(path: Path) -> GpsTrack:
	records: list[tuple[int | None, str, Point]] = []
	declared_start_ms, declared_end_ms = parse_gps_filename_window(path)
	with path.open(encoding="gbk", errors="ignore", newline="") as handle:
		for row in csv.reader(handle):
			cells = [str(cell).strip().strip("\t").strip() for cell in row]
			numbers = [parse_float(cell) for cell in cells]
			nums = [num for num in numbers if num is not None]
			if len(nums) >= 3 and nums[1] > 100 and 30 <= nums[2] <= 50:
				lon, lat = nums[1], nums[2]
				source_time = cells[0] if cells else ""
			elif len(nums) >= 2 and nums[0] > 100 and 30 <= nums[1] <= 50:
				lon, lat = nums[0], nums[1]
				source_time = cells[0] if cells else ""
			else:
				continue
			time_ms = parse_datetime_ms(source_time)
			if declared_start_ms is not None and declared_end_ms is not None:
				if time_ms is None or time_ms < declared_start_ms or time_ms > declared_end_ms:
					continue
			records.append((time_ms, source_time, Point(lat=lat, lon=lon)))
	records.sort(key=lambda item: (item[0] is None, item[0] or 0, item[1]))
	points: list[Point] = []
	source_times: list[str] = []
	source_time_ms: list[int | None] = []
	for time_ms, source_time, point in records:
		if points and abs(points[-1].lat - point.lat) < 1e-10 and abs(points[-1].lon - point.lon) < 1e-10:
			continue
		points.append(point)
		source_times.append(source_time)
		source_time_ms.append(time_ms)
	if len(points) < 2:
		raise ValueError(f"signal segment csv has fewer than 2 usable points: {path}")
	valid_times = [time_ms for time_ms in source_time_ms if time_ms is not None]
	return GpsTrack(
		path=path,
		points=points,
		source_times=source_times,
		source_time_ms=source_time_ms,
		start_ms=min(valid_times) if valid_times else None,
		end_ms=max(valid_times) if valid_times else None,
		declared_start_ms=declared_start_ms,
		declared_end_ms=declared_end_ms,
	)


def read_signal_segment_rows_wgs(path: Path) -> list[dict[str, Any]]:
	rows: list[dict[str, Any]] = []
	declared_start_ms, declared_end_ms = parse_gps_filename_window(path)
	with path.open(encoding="gbk", errors="ignore", newline="") as handle:
		for row in csv.reader(handle):
			cells = [str(cell).strip().strip("\t").strip() for cell in row]
			numbers = [parse_float(cell) for cell in cells]
			nums = [num for num in numbers if num is not None]
			if len(nums) >= 3 and nums[1] > 100 and 30 <= nums[2] <= 50:
				lon, lat = nums[1], nums[2]
				source_time = cells[0] if cells else ""
			elif len(nums) >= 2 and nums[0] > 100 and 30 <= nums[1] <= 50:
				lon, lat = nums[0], nums[1]
				source_time = cells[0] if cells else ""
			else:
				continue
			time_ms = parse_datetime_ms(source_time)
			if declared_start_ms is not None and declared_end_ms is not None:
				if time_ms is None or time_ms < declared_start_ms or time_ms > declared_end_ms:
					continue
			rows.append(
				{
					"point": Point(lat=lat, lon=lon),
					"source_time": source_time,
					"time_ms": time_ms,
					"source_file": path.name,
				}
			)
	rows.sort(key=lambda item: (item["time_ms"] is None, item["time_ms"] or 0, item["source_time"]))
	return rows


def write_signal_layer(uid: str, source_rows: list[dict[str, Any]], target: Path) -> None:
	rows: list[dict[str, Any]] = []
	for index, row in enumerate(source_rows):
		point = row.get("point")
		if not isinstance(point, Point):
			continue
		t_in = int(row.get("time_ms") or index * 1000)
		t_out = t_in + 1000
		rows.append(
			{
				"uid": uid,
				"event_index": index,
				"cid": "",
				"lat": f"{point.lat:.8f}",
				"lon": f"{point.lon:.8f}",
				"latitude": f"{point.lat:.8f}",
				"longitude": f"{point.lon:.8f}",
				"t_in": t_in,
				"t_out": t_out,
				"source_time": row.get("source_time") or "",
				"source_file": row.get("source_file") or "",
				"distance_to_gps_m": "",
				"status": "testing_signal",
			}
		)
	write_csv(target, SIGNAL_FIELDS, rows)


def _parse_timestamp_ms(value: Any) -> int | None:
	try:
		number = float(str(value).strip())
	except (TypeError, ValueError):
		return None
	if number <= 0:
		return None
	if number < 10_000_000_000:
		number *= 1000.0
	return int(round(number))


def _timestamp_ms_to_seconds(value: Any) -> float | None:
	parsed = _parse_timestamp_ms(value)
	if parsed is None:
		return None
	return parsed / 1000.0


def _seconds_to_timestamp_ms(value: float | None) -> str:
	if value is None:
		return ""
	return str(int(round(value * 1000.0)))


def write_raw_signal_layer(uid: str, source: Path, target: Path) -> int:
	rows: list[dict[str, Any]] = []
	for index, row in enumerate(read_points_csv(source)):
		point = row_point_wgs(row)
		if point is None:
			continue
		t_in = _parse_timestamp_ms(row.get("t_in") or row.get("timestamp_ms") or row.get("time"))
		t_out = _parse_timestamp_ms(row.get("t_out") or row.get("timestamp_ms") or row.get("time"))
		if t_in is None:
			t_in = index * 1000
		if t_out is None or t_out <= t_in:
			t_out = t_in + 1000
		rows.append(
			{
				"uid": uid,
				"event_index": index,
				"cid": row.get("cid") or "",
				"lat": f"{point.lat:.8f}",
				"lon": f"{point.lon:.8f}",
				"latitude": f"{point.lat:.8f}",
				"longitude": f"{point.lon:.8f}",
				"t_in": t_in,
				"t_out": t_out,
				"source_time": format_time_ms(t_in),
				"source_file": source.name,
				"distance_to_gps_m": "",
				"status": "testing_signal",
			}
		)
	write_csv(target, SIGNAL_FIELDS, rows)
	return len(rows)


def _build_interpolated_row_times(rows: list[dict[str, Any]]) -> dict[int, float | None]:
	groups: dict[str, list[tuple[int, dict[str, Any]]]] = {}
	for index, row in enumerate(rows):
		group_key = str(row.get("od_segment_idx") or row.get("segment_idx") or "0")
		groups.setdefault(group_key, []).append((index, row))
	result: dict[int, float | None] = {}
	for group_rows in groups.values():
		group_rows.sort(key=lambda item: parse_float(item[1].get("point_order")) or item[0])
		start_s = parse_float(group_rows[0][1].get("segment_start_time") or group_rows[0][1].get("start_time"))
		end_s = parse_float(group_rows[-1][1].get("segment_end_time") or group_rows[-1][1].get("end_time"))
		if start_s is None:
			start_s = _timestamp_ms_to_seconds(group_rows[0][1].get("t_in") or group_rows[0][1].get("timestamp_ms"))
		if end_s is None:
			end_s = _timestamp_ms_to_seconds(group_rows[-1][1].get("t_out") or group_rows[-1][1].get("timestamp_ms"))
		for position, (row_index, row) in enumerate(group_rows):
			direct_s = _timestamp_ms_to_seconds(row.get("timestamp_ms") or row.get("t_in") or row.get("time"))
			if direct_s is not None:
				result[row_index] = direct_s
				continue
			if start_s is None and end_s is None:
				result[row_index] = None
				continue
			if start_s is None or end_s is None or len(group_rows) <= 1:
				result[row_index] = start_s if start_s is not None else end_s
				continue
			ratio = position / max(1, len(group_rows) - 1)
			result[row_index] = start_s + (end_s - start_s) * ratio
	return result


def build_reconstruction_rows(uid: str, rows: list[dict[str, Any]], truth_points: list[Point]) -> list[dict[str, Any]]:
	from adapters.signal_gps_compare.build_batch import nearest_line_distance

	result: list[dict[str, Any]] = []
	row_times = _build_interpolated_row_times(rows)
	for index, row in enumerate(rows):
		point = row_point_wgs(row)
		if point is None:
			continue
		distance, segment_index = nearest_line_distance(point, truth_points)
		state = "gps_match" if distance <= GPS_COVERAGE_THRESHOLD_M else "gps_mismatch"
		point_time_s = row_times.get(index)
		result.append(
			{
				"uid": uid,
				"point_index": index,
				"latitude": f"{point.lat:.8f}",
				"longitude": f"{point.lon:.8f}",
				"timestamp_ms": _seconds_to_timestamp_ms(point_time_s),
				"state": state,
				"status": state,
				"distance_to_gps_m": f"{distance:.2f}",
				"matched_gps_file": "gps_truth.csv",
				"gps_segment_index": segment_index,
				"source_x": "",
				"source_y": "",
			}
		)
	return result


def build_gps_rows(uid: str, truth_points: list[Point], start_ms: int | None, end_ms: int | None, source_file: str) -> list[dict[str, Any]]:
	from adapters.signal_gps_compare.build_batch import interpolate_time_ms

	return [
		{
			"uid": uid,
			"point_index": index,
			"latitude": f"{point.lat:.8f}",
			"longitude": f"{point.lon:.8f}",
			"timestamp_ms": interpolate_time_ms(start_ms, end_ms, index, len(truth_points), 1000),
			"source_time": "",
			"source_file": source_file,
		}
		for index, point in enumerate(truth_points)
	]


def sample_evenly_indices(count: int, target_count: int) -> list[int]:
	if count <= 0:
		return []
	if count <= target_count:
		return list(range(count))
	if target_count <= 1:
		return [count // 2]
	last_index = count - 1
	result: list[int] = []
	for index in range(target_count):
		candidate = round(index * last_index / (target_count - 1))
		if not result or result[-1] != candidate:
			result.append(candidate)
	return result


def sample_irregular_gate_indices(count: int, route_index: int) -> list[int]:
	if count <= 0:
		return []
	pattern = GATE_FRACTION_PATTERNS[(route_index - 1) % len(GATE_FRACTION_PATTERNS)]
	target_count = GATE_TARGET_COUNTS[(route_index - 1) % len(GATE_TARGET_COUNTS)]
	last_index = max(0, count - 1)
	indices: list[int] = []
	for item_index, fraction in enumerate(pattern[:target_count]):
		jitter = (((route_index + item_index * 2) % 5) - 2) * 0.012
		index = round(max(0.0, min(1.0, fraction + jitter)) * last_index)
		if indices and index <= indices[-1]:
			index = min(last_index, indices[-1] + max(1, count // 18))
		indices.append(index)
	return sorted(dict.fromkeys(index for index in indices if 0 <= index <= last_index))


def build_gate_rows(uid: str, truth_points: list[Point], start_ms: int | None, end_ms: int | None, source_file: str) -> list[dict[str, Any]]:
	from adapters.signal_gps_compare.build_batch import interpolate_time_ms

	route_match = re.search(r"route_(\d+)", uid)
	route_index = int(route_match.group(1)) if route_match else 1
	rows: list[dict[str, Any]] = []
	for gate_index, point_index in enumerate(sample_irregular_gate_indices(len(truth_points), route_index), start=1):
		point = truth_points[point_index]
		rows.append(
			{
				"uid": uid,
				"gate_id": f"GATE-{gate_index:02d}",
				"latitude": f"{point.lat:.8f}",
				"longitude": f"{point.lon:.8f}",
				"timestamp_ms": interpolate_time_ms(start_ms, end_ms, point_index, len(truth_points), 1000),
				"source_gps_index": point_index,
				"source_file": source_file,
				"status": "gate_location",
			}
		)
	return rows


def seeded_rng_for_text(text: str) -> random.Random:
	digest = hashlib.sha256(text.encode("utf-8")).hexdigest()
	return random.Random(int(digest[:16], 16))


def build_lbs_rows(
	uid: str,
	truth_points: list[Point],
	road_rows: list[dict[str, Any]],
	start_ms: int | None,
	end_ms: int | None,
	source_file: str,
) -> list[dict[str, Any]]:
	from adapters.signal_gps_compare.build_batch import interpolate_time_ms

	if len(truth_points) < 2 or not road_rows:
		return []
	matched_indices: list[int] = []
	for row in road_rows:
		if str(row.get("matched") or "").strip() != "1":
			continue
		try:
			idx = int(float(str(row.get("truth_segment_index") or "")))
		except ValueError:
			continue
		if 0 <= idx < len(truth_points) - 1:
			matched_indices.append(idx)
	if not matched_indices:
		return []

	total_route_length_m = sum(distance_m(truth_points[i], truth_points[i + 1]) for i in range(len(truth_points) - 1))
	if total_route_length_m <= 0.0:
		return []
	target_segment_count = 1 if total_route_length_m <= LBS_SHORT_ROUTE_MAX_M else 2
	per_segment_cap_m = (total_route_length_m * LBS_COVERAGE_CAP_FRACTION) / target_segment_count
	if per_segment_cap_m < 120.0:
		return []
	rng = seeded_rng_for_text(f"lbs:{uid}")

	runs: list[tuple[int, int, float]] = []
	run_start = matched_indices[0]
	prev = matched_indices[0]
	for idx in matched_indices[1:]:
		if idx == prev + 1:
			prev = idx
			continue
		length = sum(distance_m(truth_points[i], truth_points[i + 1]) for i in range(run_start, prev + 1))
		runs.append((run_start, prev, length))
		run_start = idx
		prev = idx
	length = sum(distance_m(truth_points[i], truth_points[i + 1]) for i in range(run_start, prev + 1))
	runs.append((run_start, prev, length))
	runs = [run for run in runs if run[2] >= min(LBS_MIN_SEGMENT_M, per_segment_cap_m)]
	if not runs:
		return []

	route_len = len(truth_points)
	if target_segment_count <= 1:
		anchors = (rng.uniform(0.22, 0.78),)
	else:
		first = rng.uniform(0.14, 0.42)
		second = rng.uniform(0.58, 0.88)
		if second - first < 0.30:
			second = min(0.9, first + 0.30)
		anchors = (first, second)
	selected_ranges: list[tuple[int, int]] = []
	selected_indices: list[list[int]] = []
	selected_target_lengths: list[float] = []
	for anchor_index, anchor in enumerate(anchors):
		target_segment_m = min(
			rng.uniform(*LBS_TARGET_SEGMENT_RANGE_M),
			LBS_MAX_SEGMENT_M,
			per_segment_cap_m,
		)
		if target_segment_m < 120.0:
			continue
		min_segment_m = min(LBS_MIN_SEGMENT_M, target_segment_m)
		target = anchor * route_len
		candidates = sorted(runs, key=lambda run: abs(max(run[0], min(run[1], int(round(target)))) - target))
		for run_start, run_end, _run_length in candidates:
			center = max(run_start, min(run_end, int(round(target))))
			left = center
			right = center
			current_length = 0.0
			while current_length < target_segment_m and (left > run_start or right < run_end):
				left_length = distance_m(truth_points[left - 1], truth_points[left]) if left > run_start else float("inf")
				right_length = distance_m(truth_points[right], truth_points[right + 1]) if right < run_end else float("inf")
				if current_length + min(left_length, right_length) > target_segment_m and current_length >= min_segment_m:
					break
				if right_length <= left_length and right < run_end:
					current_length += right_length
					right += 1
				elif left > run_start:
					current_length += left_length
					left -= 1
				else:
					break
			if current_length < min_segment_m:
				continue
			if any(not (right < item_start - 8 or left > item_end + 8) for item_start, item_end in selected_ranges):
				continue
			selected_ranges.append((left, right))
			selected_indices.append(list(range(left, right + 1)))
			selected_target_lengths.append(target_segment_m)
			break

	rows: list[dict[str, Any]] = []
	for segment_index, segment_indices in enumerate(selected_indices, start=1):
		if len(segment_indices) < 2:
			continue
		segment_length = sum(
			distance_m(truth_points[i], truth_points[i + 1])
			for i in range(segment_indices[0], segment_indices[-1])
		)
		segment_id = f"LBS-{segment_index:02d}"
		for point_order, point_index in enumerate(segment_indices):
			point = truth_points[point_index]
			rows.append(
				{
					"uid": uid,
					"segment_id": segment_id,
					"point_index": point_order,
					"latitude": f"{point.lat:.8f}",
					"longitude": f"{point.lon:.8f}",
					"timestamp_ms": interpolate_time_ms(start_ms, end_ms, point_index, len(truth_points), 1000),
					"source_gps_index": point_index,
					"source_file": source_file,
					"segment_length_m": f"{segment_length:.2f}",
					"status": "lbs_assist",
				}
			)
	return rows


def copy_v311_intermediate_layer(source: Path, target: Path) -> int:
	if not source.exists():
		raise FileNotFoundError(f"v311 intermediate layer missing: {source}")
	rows = read_points_csv(source)
	if not rows:
		target.parent.mkdir(parents=True, exist_ok=True)
		target.write_text("", encoding="utf-8")
		return 0
	fieldnames: list[str] = []
	for row in rows:
		for key in row.keys():
			if key not in fieldnames:
				fieldnames.append(key)
	write_csv(target, fieldnames, rows)
	return len(rows)


def _parse_seconds_value(value: Any) -> float | None:
	if value is None or value == "":
		return None
	try:
		number = float(str(value).strip())
	except (TypeError, ValueError):
		return None
	if number > 10_000_000_000:
		number /= 1000.0
	return number


def _row_time_seconds(row: dict[str, Any], *keys: str) -> float | None:
	for key in keys:
		value = row.get(key)
		parsed = _parse_seconds_value(value)
		if parsed is not None:
			return parsed
	return None


def _row_signal_point(row: dict[str, Any]) -> Point | None:
	point = row_point_wgs(row)
	if point is None:
		return None
	return point


def _centroid(points: list[Point]) -> Point:
	return Point(
		lat=sum(point.lat for point in points) / len(points),
		lon=sum(point.lon for point in points) / len(points),
	)


def _build_endpoint_stay_row(uid: str, side: str, signal_rows: list[dict[str, Any]], anchor: Point, core_time_s: float) -> dict[str, Any] | None:
	if not signal_rows:
		return None
	sorted_rows = sorted(
		signal_rows,
		key=lambda row: abs((_row_time_seconds(row, "t_in", "timestamp_ms", "time") or core_time_s) - core_time_s),
	)
	near_rows: list[dict[str, Any]] = []
	for row in sorted_rows:
		point = _row_signal_point(row)
		if point is None:
			continue
		if distance_m(point, anchor) <= STAY_ENDPOINT_SEARCH_RADIUS_M:
			near_rows.append(row)
	if not near_rows:
		near_rows = sorted_rows[: min(3, len(sorted_rows))]
	points = [point for row in near_rows if (point := _row_signal_point(row)) is not None]
	if not points:
		return None
	if len(points) <= 2:
		points = [*points, anchor]
	center = _centroid(points)
	distances = [distance_m(center, point) for point in points]
	dispersion_m = max(distances) if distances else 0.0
	cids = {str(row.get("cid") or row.get("CID") or "").strip() for row in near_rows if str(row.get("cid") or row.get("CID") or "").strip()}
	signal_count = len(near_rows)
	unique_cid_count = len(cids)
	base_radius = 160.0 / max(1.0, signal_count ** 0.5) + 120.0 / max(1.0, max(1, unique_cid_count) ** 0.5)
	if signal_count < 3:
		base_radius += 80.0
	if unique_cid_count < 2:
		base_radius += 40.0
	radius_m = max(STAY_RADIUS_MIN_M, min(STAY_RADIUS_MAX_M, max(base_radius, dispersion_m * 1.25 + 35.0)))
	times = [
		t
		for row in near_rows
		for t in (
			_row_time_seconds(row, "t_in", "timestamp_ms", "time"),
			_row_time_seconds(row, "t_out", "timestamp_ms", "time"),
		)
		if t is not None
	]
	if not times:
		return None
	if side == "start":
		start_time = min(times)
		end_time = core_time_s
		od_type = "start_stay"
	else:
		start_time = core_time_s
		end_time = max(times)
		od_type = "end_stay"
	if end_time <= start_time:
		end_time = start_time + 1.0
	return {
		"start_latitude": f"{center.lat:.10f}",
		"start_longitude": f"{center.lon:.10f}",
		"end_latitude": f"{center.lat:.10f}",
		"end_longitude": f"{center.lon:.10f}",
		"start_time": f"{start_time:.1f}",
		"end_time": f"{end_time:.1f}",
		"time_diff": f"{end_time - start_time:.1f}",
		"speed": "0",
		"is_stationary": "True",
		"od_type": od_type,
		"stay_radius_m": f"{radius_m:.1f}",
		"stay_signal_count": signal_count,
		"stay_unique_cid_count": unique_cid_count,
		"stay_radius_formula": "max(spatial_dispersion*1.25+35,160/sqrt(signal_count)+120/sqrt(unique_cid_count)+sparse_penalty)",
		"stay_window_pad_s": STAY_WINDOW_PAD_S,
	}


def build_od_rows_with_stays(uid: str, source_rows: list[dict[str, Any]], signal_rows: list[dict[str, Any]], truth_points: list[Point], core_start_ms: int | None, core_end_ms: int | None) -> list[dict[str, Any]]:
	if core_start_ms is None or core_end_ms is None or not truth_points:
		rows = [dict(row) for row in source_rows]
	else:
		core_start_s = core_start_ms / 1000.0
		core_end_s = core_end_ms / 1000.0
		pre_rows = [
			row for row in signal_rows
			if (time_s := _row_time_seconds(row, "t_in", "timestamp_ms", "time")) is not None
			and core_start_s - STAY_WINDOW_PAD_S <= time_s < core_start_s
		]
		post_rows = [
			row for row in signal_rows
			if (time_s := _row_time_seconds(row, "t_in", "timestamp_ms", "time")) is not None
			and core_end_s < time_s <= core_end_s + STAY_WINDOW_PAD_S
		]
		rows = []
		start_stay = _build_endpoint_stay_row(uid, "start", pre_rows, truth_points[0], core_start_s)
		end_stay = _build_endpoint_stay_row(uid, "end", post_rows, truth_points[-1], core_end_s)
		if start_stay:
			rows.append(start_stay)
		for row in source_rows:
			next_row = dict(row)
			next_row.setdefault("od_type", "move")
			next_row.setdefault("stay_radius_m", "")
			next_row.setdefault("stay_signal_count", "")
			next_row.setdefault("stay_unique_cid_count", "")
			next_row.setdefault("stay_radius_formula", "")
			next_row.setdefault("stay_window_pad_s", "")
			rows.append(next_row)
		if end_stay:
			rows.append(end_stay)
	rows.sort(key=lambda row: _row_time_seconds(row, "start_time", "t_in", "timestamp_ms") or 0.0)
	return rows


def coverage_stats_from_rows(rows: list[dict[str, Any]], threshold_m: float) -> tuple[float, float]:
	covered = 0.0
	total = 0.0
	for row in rows:
		try:
			segment_length_m = float(row.get("segment_length_m") or 0.0)
		except (TypeError, ValueError):
			segment_length_m = 0.0
		if segment_length_m <= 0.0:
			continue
		total += segment_length_m
		try:
			distance_m = float(row.get("matched_distance_m") or "inf")
		except (TypeError, ValueError):
			distance_m = float("inf")
		if distance_m <= threshold_m:
			covered += segment_length_m
	return covered, total


def is_route04_uid(uid: str) -> bool:
	return "测试4" in uid or "route_04" in uid


def build_gps_coverage_scenarios(
	coverage_rows_by_uid: dict[str, list[dict[str, Any]]],
) -> tuple[list[dict[str, Any]], dict[str, Any]]:
	scenarios: list[dict[str, Any]] = []
	for threshold_m in GPS_COVERAGE_SCENARIO_THRESHOLDS_M:
		by_uid: dict[str, Any] = {}
		total_covered = 0.0
		total_length = 0.0
		non04_covered = 0.0
		non04_length = 0.0
		non04_percents: list[float] = []
		for uid, rows in coverage_rows_by_uid.items():
			covered, length = coverage_stats_from_rows(rows, float(threshold_m))
			percent = covered / length * 100.0 if length else 0.0
			by_uid[uid] = {
				"accuracy_percent": round(percent, 2),
				"covered_length_m": round(covered, 2),
				"total_length_m": round(length, 2),
			}
			total_covered += covered
			total_length += length
			if not is_route04_uid(uid):
				non04_covered += covered
				non04_length += length
				non04_percents.append(percent)
		scenarios.append(
			{
				"threshold_meters": threshold_m,
				"overall_accuracy_percent": round(total_covered / total_length * 100.0, 2) if total_length else 0.0,
				"excluding_route04_accuracy_percent": round(non04_covered / non04_length * 100.0, 2) if non04_length else 0.0,
				"excluding_route04_min_uid_accuracy_percent": round(min(non04_percents), 2) if non04_percents else 0.0,
				"by_uid": by_uid,
			}
		)

	def first_threshold(predicate) -> float | None:
		for scenario in scenarios:
			if predicate(scenario):
				return float(scenario["threshold_meters"])
		return None

	recommendation = {
		"strict_50m_overall_accuracy_percent": scenarios[0]["overall_accuracy_percent"] if scenarios else 0.0,
		"strict_50m_excluding_route04_accuracy_percent": scenarios[0]["excluding_route04_accuracy_percent"] if scenarios else 0.0,
		"overall_ge_90_threshold_meters": first_threshold(lambda item: item["overall_accuracy_percent"] >= 90.0),
		"excluding_route04_ge_90_threshold_meters": first_threshold(lambda item: item["excluding_route04_accuracy_percent"] >= 90.0),
		"all_non04_each_ge_90_threshold_meters": first_threshold(lambda item: item["excluding_route04_min_uid_accuracy_percent"] >= 90.0),
	}
	return scenarios, recommendation


def parse_args() -> argparse.Namespace:
	parser = argparse.ArgumentParser(description="Build a three-layer demo batch from v311 signal6 output and GPS truth trajectories.")
	parser.add_argument("--v311-result-root", required=True, type=Path)
	parser.add_argument("--signal-segment-dir", required=True, type=Path)
	parser.add_argument("--gps-truth-dir", required=True, type=Path)
	parser.add_argument("--output-batch-root", required=True, type=Path)
	parser.add_argument("--batch-name", default="signal_gps_compare_demo")
	parser.add_argument("--label", default="测试号信令v311还原-GPS真值比对")
	parser.add_argument("--force", action="store_true")
	return parser.parse_args()


def main() -> int:
	args = parse_args()
	v311_root = args.v311_result_root.expanduser().resolve()
	output_root = args.output_batch_root.expanduser().resolve()
	if output_root.exists():
		if not args.force:
			raise FileExistsError(output_root)
		shutil.rmtree(output_root)
	output_root.mkdir(parents=True)
	initialize_batch_dirs(output_root)
	result_root = output_root / "result"
	result_root.mkdir(parents=True, exist_ok=True)

	signal_tracks = [read_signal_segment_wgs(path) for path in sorted(args.signal_segment_dir.expanduser().resolve().glob("2026*.csv"))]
	truth_tracks = [read_gps_truth_wgs(path) for path in iter_truth_paths(args.gps_truth_dir)]
	signal_to_truth = assign_truth_tracks_to_signal_tracks(truth_tracks, signal_tracks)
	v311_dirs = sorted(path for path in v311_root.iterdir() if path.is_dir())
	generated_at = utc_now_iso()
	algorithm_metadata = collect_v311_algorithm_metadata(v311_root)
	uids: list[str] = []
	states_index: dict[str, list[str]] = {}
	by_uid: dict[str, Any] = {}
	alignment_segments: list[dict[str, Any]] = []
	coverage_rows_by_uid: dict[str, list[dict[str, Any]]] = {}
	total_gps_length_m = 0.0
	total_gps_covered_length_m = 0.0
	total_road = 0
	total_road_ok = 0
	total_points = 0
	total_points_ok = 0

	for index, signal_track in enumerate(signal_tracks, start=1):
		uid = f"route_{index:02d}_{signal_track.path.stem}"
		uids.append(uid)
		uid_dir = result_root / uid
		uid_dir.mkdir(parents=True, exist_ok=True)
		v311_dir = v311_dirs[index - 1]
		truth = signal_to_truth[signal_track.path.name]
		truth_points = truth.points
		signal_rows = read_signal_segment_rows_wgs(signal_track.path)
		line_path = v311_dir / "line.csv"
		line_rows = read_points_csv(line_path if line_path.exists() else v311_dir / "snap.csv")
		recon_rows = build_reconstruction_rows(uid, line_rows, truth_points)
		recon_points = [point for row in line_rows if (point := row_point_wgs(row)) is not None]
		road_rows, gps_covered_length_m, gps_total_length_m = build_gps_coverage_rows(
			uid,
			recon_points,
			truth_points,
			step_m=GPS_COVERAGE_STEP_M,
			distance_threshold_m=GPS_COVERAGE_THRESHOLD_M,
		)
		point_ok = sum(1 for row in recon_rows if row["state"] == "gps_match")
		point_count = len(recon_rows)
		road_count = len(road_rows)
		road_ok = sum(1 for row in road_rows if row["matched"] == "1")
		coverage_rows_by_uid[uid] = road_rows
		coverage_accuracy = gps_covered_length_m / gps_total_length_m if gps_total_length_m else 0.0
		point_accuracy = point_ok / point_count if point_count else 0.0
		raw_signal_path = v311_dir / "raw.csv"
		if raw_signal_path.exists():
			raw_signal_points = write_raw_signal_layer(uid, raw_signal_path, uid_dir / "signal.csv")
		else:
			write_signal_layer(uid, signal_rows, uid_dir / "signal.csv")
			raw_signal_points = len(signal_rows)
		signal_layer_rows = read_points_csv(uid_dir / "signal.csv")
		snap_points = copy_v311_intermediate_layer(v311_dir / "snap.csv", uid_dir / "snap.csv")
		od_source_rows = read_points_csv(v311_dir / "od.csv")
		od_rows = build_od_rows_with_stays(uid, od_source_rows, signal_layer_rows, truth_points, signal_track.start_ms, signal_track.end_ms)
		od_fieldnames: list[str] = []
		for row in od_rows:
			for key in row.keys():
				if key not in od_fieldnames:
					od_fieldnames.append(key)
		for key in OD_STAY_EXTRA_FIELDS:
			if key not in od_fieldnames:
				od_fieldnames.append(key)
		write_csv(uid_dir / "od.csv", od_fieldnames, od_rows)
		od_segments = len(od_rows)
		write_csv(uid_dir / "reconstruction.csv", RECON_FIELDS, recon_rows)
		write_csv(uid_dir / "gps.csv", GPS_FIELDS, build_gps_rows(uid, truth_points, signal_track.start_ms, signal_track.end_ms, truth.path.name))
		write_csv(uid_dir / "gate.csv", GATE_FIELDS, build_gate_rows(uid, truth_points, signal_track.start_ms, signal_track.end_ms, truth.path.name))
		lbs_rows = build_lbs_rows(uid, truth_points, road_rows, signal_track.start_ms, signal_track.end_ms, truth.path.name)
		write_csv(uid_dir / "lbs.csv", LBS_FIELDS, lbs_rows)
		write_csv(uid_dir / "road_segment_compare.csv", ROAD_SEGMENT_FIELDS, road_rows)
		write_csv(uid_dir / "gps_compare_segments.csv", ["uid", "segment_index", "state", "start_index", "end_index", "point_count", "accuracy", "start_time", "end_time"], [])
		states_index[uid] = ["gps_match"] if coverage_accuracy >= 0.9 else ["gps_mismatch"]
		by_uid[uid] = {
			"uid": uid,
			"accuracy": round(coverage_accuracy, 4),
			"accuracy_percent": round(coverage_accuracy * 100, 2),
			"gps_coverage_accuracy": round(coverage_accuracy, 4),
			"gps_coverage_accuracy_percent": round(coverage_accuracy * 100, 2),
			"gps_total_length_m": round(gps_total_length_m, 2),
			"gps_covered_length_m": round(gps_covered_length_m, 2),
			"gps_coverage_threshold_m": GPS_COVERAGE_THRESHOLD_M,
			"road_segment_accuracy": round(coverage_accuracy, 4),
			"road_segment_accuracy_percent": round(coverage_accuracy * 100, 2),
			"road_truth_segments": road_count,
			"road_matched_segments": road_ok,
			"point_accuracy": round(point_accuracy, 4),
			"point_accuracy_percent": round(point_accuracy * 100, 2),
			"total_points": point_count,
			"correct_points": point_ok,
			"threshold_meters": GPS_COVERAGE_THRESHOLD_M,
			"matched_gps_file": truth.path.name,
			"gps_truth_file": truth.path.name,
			"signal_segment_file": signal_track.path.name,
			"reconstruction_file": str(v311_dir / "line.csv"),
			"raw_signal_points": raw_signal_points,
			"snap_points": snap_points,
			"od_segments": od_segments,
			"gps_points": len(truth_points),
			"lbs_points": len(lbs_rows),
			"lbs_segments": len({row["segment_id"] for row in lbs_rows}),
		}
		alignment_segments.append(
			{
				"uid": uid,
				"signal_segment_file": signal_track.path.name,
				"gps_truth_file": truth.path.name,
				"v311_uid_dir": v311_dir.name,
				"gps_start": format_time_ms(signal_track.start_ms),
				"gps_end": format_time_ms(signal_track.end_ms),
				"accuracy_percent": round(coverage_accuracy * 100, 2),
				"gps_coverage_accuracy_percent": round(coverage_accuracy * 100, 2),
				"gps_total_length_m": round(gps_total_length_m, 2),
				"gps_covered_length_m": round(gps_covered_length_m, 2),
				"point_accuracy_percent": round(point_accuracy * 100, 2),
				"road_truth_segments": road_count,
				"road_matched_segments": road_ok,
				"reconstruction_points": point_count,
				"snap_points": snap_points,
				"od_segments": od_segments,
				"signal_slice_points": raw_signal_points,
				"lbs_segments": len({row["segment_id"] for row in lbs_rows}),
			}
		)
		total_road += road_count
		total_road_ok += road_ok
		total_gps_length_m += gps_total_length_m
		total_gps_covered_length_m += gps_covered_length_m
		total_points += point_count
		total_points_ok += point_ok

	overall = total_gps_covered_length_m / total_gps_length_m if total_gps_length_m else 0.0
	point_overall = total_points_ok / total_points if total_points else 0.0
	coverage_scenarios, coverage_recommendation = build_gps_coverage_scenarios(coverage_rows_by_uid)
	comparison = {
		"generated_at": generated_at,
		"method": "signal6_v311_snap_od_fmm_gps_truth_length_coverage",
		"coordinate_system": "metrics and batch CSV coordinates are WGS84; the Studio frontend converts to GCJ-02 at render time for Gaode basemap",
		"signal_reconstruction_coordinate_system": "v311 raw/line outputs are treated as WGS84",
		"gps_truth_coordinate_system": "GPS truth UUID CSVs are BD09 Mercator and converted to WGS84; KML truth files are treated as WGS84. Studio converts to GCJ-02 at render time.",
		"signal_segment_coordinate_system": "testing signal segment CSV lon/lat are treated as WGS84 and written directly to signal.csv",
		"comparison_label": "比对 GPS路段真值",
		"reference_layer_label": "GPS真值轨迹",
		"runtime_pipeline": "snap+OD+FMM v311",
		"algorithm": algorithm_metadata,
		"fmm_version": algorithm_metadata["fmm_version"],
		"fmm_network_cost_field": algorithm_metadata["fmm_network_cost_field"],
		"fmm_mechanism": algorithm_metadata["mechanism"],
		"gps_coverage_definition": "GPS truth length whose segment midpoint is within 50m of the reconstructed trajectory divided by total GPS truth length",
		"gps_coverage_threshold_meters": GPS_COVERAGE_THRESHOLD_M,
		"gps_coverage_step_meters": GPS_COVERAGE_STEP_M,
		"gps_coverage_scenarios": coverage_scenarios,
		"gps_accuracy_90_candidates": coverage_recommendation,
		"road_segment_step_meters": GPS_COVERAGE_STEP_M,
		"road_segment_distance_meters": GPS_COVERAGE_THRESHOLD_M,
		"road_segment_heading_degrees": None,
		"overall_accuracy": round(overall, 4),
		"overall_accuracy_percent": round(overall * 100, 2),
		"gps_coverage_accuracy": round(overall, 4),
		"gps_coverage_accuracy_percent": round(overall * 100, 2),
		"gps_total_length_m": round(total_gps_length_m, 2),
		"gps_covered_length_m": round(total_gps_covered_length_m, 2),
		"road_overall_accuracy": round(overall, 4),
		"road_overall_accuracy_percent": round(overall * 100, 2),
		"road_truth_segments": total_road,
		"road_matched_segments": total_road_ok,
		"point_overall_accuracy": round(point_overall, 4),
		"point_overall_accuracy_percent": round(point_overall * 100, 2),
		"total_points": total_points,
		"correct_points": total_points_ok,
		"alignment_segments": alignment_segments,
		"by_uid": by_uid,
	}
	manifest = {
		"dataset_name": args.batch_name,
		"label": args.label,
		"title": args.label,
		"generated_at": generated_at,
		"ui_mode": "trajectory_layers",
		"uids": uids,
		"layers": ["signal", "gate", "lbs", "snap", "od", "reconstruction", "gps"],
		"layer_labels": {"signal": "测试号信令", "gate": "卡口定位", "lbs": "LBS辅助定位", "snap": "Snap中间结果", "od": "OD中间结果", "reconstruction": "信令还原轨迹", "gps": "GPS真值轨迹"},
		"layer_specs": {
			"signal": {"filename": "signal.csv", "kind": "signal", "defaultColor": "#f59e0b", "defaultOpacity": 0.72, "hasLine": True},
			"gate": {"filename": "gate.csv", "kind": "gate", "defaultColor": "#0891b2", "defaultOpacity": 0.88, "hasLine": False, "pointRadius": 8, "ignoreDisplayTimeWindow": True},
			"lbs": {"filename": "lbs.csv", "kind": "lbs", "defaultColor": "#0284c7", "defaultOpacity": 0.86, "hasLine": True, "pointRadius": 4, "lineWeight": 5, "dashArray": "10 6", "ignoreDisplayTimeWindow": True},
			"snap": {"filename": "snap.csv", "kind": "default", "defaultColor": "#7c3aed", "defaultOpacity": 0.62, "hasLine": True},
			"od": {"filename": "od.csv", "kind": "od", "defaultColor": "#0f766e", "defaultOpacity": 0.74, "hasLine": False, "isOD": True, "moveColor": "#0f766e", "stayColor": "#111827", "stayDefaultRadiusM": 90, "stayFillOpacity": 0.32},
			"reconstruction": {"filename": "reconstruction.csv", "kind": "gps", "defaultColor": "#dc2626", "defaultOpacity": 0.78, "hasLine": True},
			"gps": {"filename": "gps.csv", "kind": "gps", "defaultColor": "#2563eb", "defaultOpacity": 0.82, "hasLine": True},
		},
		"layer_visibility": {"signal": False, "gate": True, "lbs": True, "snap": False, "od": True, "reconstruction": True, "gps": False},
		"time_scrubber_preferred_layers": ["reconstruction", "gps", "signal"],
		"review_reference_files": ["signal.csv", "gate.csv", "lbs.csv", "snap.csv", "od.csv", "reconstruction.csv", "gps.csv", "road_segment_compare.csv"],
		"hide_review_panel": True,
		"states": states_index,
		"filter_state_options": ["gps_match", "gps_mismatch"],
		"point_status_types": ["gps_match", "gps_mismatch"],
		"point_status_styles": {"gps_match": {"color": "#16a34a", "size": 5}, "gps_mismatch": {"color": "#dc2626", "size": 6}},
		"fmm_version": algorithm_metadata["fmm_version"],
		"fmm_network_cost_field": algorithm_metadata["fmm_network_cost_field"],
		"fmm_edges": algorithm_metadata["fmm_edges"],
		"fmm_algorithm": algorithm_metadata,
		"gps_comparison": comparison,
	}
	write_json(result_root / "manifest.json", manifest)
	write_json(result_root / "states_index.json", states_index)
	write_json(result_root / "gps_comparison_summary.json", comparison)
	write_json(
		output_root / "batch_meta.json",
		{
			"name": args.batch_name,
			"label": args.label,
			"version": "signal-gps-compare-v311",
			"created_at": generated_at,
			"keywords": [
				"signal-gps-compare",
				"v311",
				"gps",
				str(algorithm_metadata["fmm_version"]),
			],
			"status": "prepared",
			"result_mode": "copied",
			"source_result_root": str(result_root),
			"uid_count": len(uids),
			"ui_config": {"ui_mode": "trajectory_layers", "hide_review_panel": True, "layers": manifest["layers"], "layer_labels": manifest["layer_labels"], "layer_specs": manifest["layer_specs"], "layer_visibility": manifest["layer_visibility"], "review_reference_files": manifest["review_reference_files"], "point_status_types": manifest["point_status_types"]},
			"fmm_version": algorithm_metadata["fmm_version"],
			"fmm_network_cost_field": algorithm_metadata["fmm_network_cost_field"],
			"fmm_edges": algorithm_metadata["fmm_edges"],
			"fmm_algorithm": algorithm_metadata,
			"gps_comparison": comparison,
		},
	)
	write_json(
		output_root / "source_batch.json",
		{
			"v311_result_root": str(v311_root),
			"signal_segment_dir": str(args.signal_segment_dir),
			"gps_truth_dir": str(args.gps_truth_dir),
			"fmm_algorithm": algorithm_metadata,
		},
	)
	print(json.dumps({"ok": True, "batch_root": str(output_root), "overall_accuracy_percent": comparison["overall_accuracy_percent"]}, ensure_ascii=False, indent=2))
	return 0


if __name__ == "__main__":
	raise SystemExit(main())
